#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.DownloadDiagnostics."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_DownloadDiagnostics"

UCI_GET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state get"
UCI_SET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state set"

entry_execute_method_root_DownloadDiagnostics() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.DownloadDiagnostics."*)
		common_execute_method_obj "$DMROOT.DownloadDiagnostics." "0"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.DiagnosticsState" "1" "download_get easycwmp.@local[0].DiagnosticsState_download None" "download_set_diagnostic_state"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.Interface" "1" "download_get easycwmp.@local[0].Interface_download" "download_set easycwmp.@local[0].Interface_download"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.DownloadURL" "1" "download_get easycwmp.@local[0].downloadurl" "download_set easycwmp.@local[0].downloadurl"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.DSCP" "1" "download_get easycwmp.@local[0].DSCP_download 0" "download_set_number easycwmp.@local[0].DSCP_download" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.EthernetPriority" "1" "download_get easycwmp.@local[0].ethernetpriority 0" "download_set_number easycwmp.@local[0].ethernetpriority" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.ROMTime" "0" "download_get easycwmp.@local[0].romtime_download" "" "xsd:dateTime"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.BOMTime" "0" "download_get easycwmp.@local[0].bomtime_download" "" "xsd:dateTime"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.EOMTime" "0" "download_get easycwmp.@local[0].eomtime_download" "" "xsd:dateTime"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.TestBytesReceived" "0" "download_get easycwmp.@local[0].testrx_download" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.TotalBytesReceived" "0" "download_get easycwmp.@local[0].totalrx_download" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.TCPOpenRequestTime" "0" "download_get easycwmp.@local[0].tcpopenrequesttime_download" "" "xsd:dateTime"
		common_execute_method_param "$DMROOT.DownloadDiagnostics.TCPOpenResponseTime" "0" "download_get easycwmp.@local[0].tcpopenresponsetime_download" "" "xsd:dateTime"
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#   Data model parameters functions   #
#######################################

download_get() {
	local val=`$UCI_GET_VARSTATE $1`
	echo ${val:-$2}
}

download_set() {
	download_stop_diagnostic
	if [ "`$UCI_GET_VARSTATE easycwmp.@local[0].DiagnosticsState_download`" != "Requested" ]; then
		$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_download=None
	fi
	$UCI_SET_VARSTATE $1=$2
	return 0
}

download_set_number() {
	case $2 in
		(*[^0-9]*|'') return $E_INVALID_PARAMETER_VALUE;;
	esac
	[ $2 -lt 1 ] && return $E_INVALID_PARAMETER_VALUE
	download_stop_diagnostic
	if [ "`$UCI_GET_VARSTATE easycwmp.@local[0].DiagnosticsState_download`" != "Requested" ]; then
		$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_download=None
	fi
	$UCI_SET_VARSTATE $1=$2
	return 0
}

download_set_diagnostic_state() {
	local val="$1"
	case $val in 
		Requested)
			download_stop_diagnostic
			$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_download=Requested
			common_execute_command_in_apply_service "/bin/sh $FUNCTION_PATH/download_launch run &"
			return 0
		;;
	esac
	return $E_INVALID_PARAMETER_VALUE;
}

download_stop_diagnostic() {
	local pids=`ps aux | grep download_launch | grep -v grep | awk '{print $2}'`
	if [ -n "$pids" ]; then
		kill -9 $pids
		$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_download=None
	fi
}


