#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.TraceRouteDiagnostics."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_TraceRouteDiagnostics"

UCI_GET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state get"
UCI_SET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state set"

entry_execute_method_root_TraceRouteDiagnostics() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.TraceRouteDiagnostics."*)
		common_execute_method_obj "$DMROOT.TraceRouteDiagnostics." "0"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.DiagnosticsState" "1" "traceroute_get easycwmp.@local[0].DiagnosticsState_trace None" "traceroute_set_diagnostic_state"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.Interface" "1" "traceroute_get easycwmp.@local[0].Interface_trace" "traceroute_set easycwmp.@local[0].Interface_trace"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.Host" "1" "traceroute_get easycwmp.@local[0].Host_trace" "traceroute_set easycwmp.@local[0].Host_trace"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.NumberOfTries" "1" "traceroute_get easycwmp.@local[0].NumberOfTries_trace 3" "traceroute_set_number easycwmp.@local[0].NumberOfTries_trace" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.Timeout" "1" "traceroute_get easycwmp.@local[0].Timeout_trace 5000" "traceroute_set_number easycwmp.@local[0].Timeout_trace" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.DataBlockSize" "1" "traceroute_get easycwmp.@local[0].DataBlockSize_trace 38" "traceroute_set_number easycwmp.@local[0].DataBlockSize_trace" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.DSCP" "1" "traceroute_get easycwmp.@local[0].DSCP_trace 0" "traceroute_set_number easycwmp.@local[0].DSCP_trace" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.MaxHopCount" "1" "traceroute_get easycwmp.@local[0].MaxHopCount_trace 30" "traceroute_set_number easycwmp.@local[0].MaxHopCount_trace" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.ResponseTime" "0" "traceroute_get easycwmp.@local[0].ResponseTime_trace 0" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.RouteHopsNumberOfEntries" "0" "traceroute_get easycwmp.@local[0].RouteHopsNumberOfEntries_trace 0" "" "xsd:unsignedInt"
		
		common_execute_method_obj "$DMROOT.TraceRouteDiagnostics.RouteHops." "0" "" "" "traceroute_diagnostics_browse_instances_routehops $1"
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_routehops() {
	local j="$2"
	local line_value="$3"
	local value1=`echo "$line_value" | awk -F ' ' '{ print $2 }'`
	local value2=`echo "$line_value" | awk -F ' ' '{ print $3 }' | sed 's/[()]//g`
	local value3=""
	local value4=`echo "$line_value" | awk -F ' ' '{ print $4 }'`
	
	local line="$value1&$value2&$value3&$value4"
	
	case_param "$1" belongto "$DMROOT.TraceRouteDiagnostics.RouteHops.$j." && {
		common_execute_method_obj "$DMROOT.TraceRouteDiagnostics.RouteHops.$j." "0" "" ""
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.RouteHops.$j.HopHost" "0" "get_hophost $line" "" "xsd:String" "0"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.RouteHops.$j.HopHostAddress" "0" "get_hophost_address $line" "" "xsd:String" "0"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.RouteHops.$j.HopErrorCode" "0" "get_hop_error_code $line" "" "xsd:unsignedInt" "0"
		common_execute_method_param "$DMROOT.TraceRouteDiagnostics.RouteHops.$j.HopRTTimes" "0" "get_hop_rttimes $line" "" "xsd:String" "0"
		return 0
	}
	return $E_INVALID_PARAMETER_NAME;
}
#######################################
#   Data model parameters functions   #
#######################################
get_hophost() {
	local line="$1"
	local hophost=`echo "$line" | awk -F '&' '{ print $1 }'`
	
	echo "$hophost"
}

get_hophost_address() {
	local line="$1"
	local hophost_address=`echo "$line" | awk -F '&' '{ print $2 }'`
	
	echo "$hophost_address"	
}

get_hop_error_code() {
	local line="$1"
	local hop_error_code=`echo "$line" | awk -F '&' '{ print $3 }'`
	
	echo "$hop_error_code"	
}

get_hop_rttimes() {
	local line="$1"
	local hop_rttimes=`echo "$line" | awk -F '&' '{ print $4 }'`
	
	echo "$hop_rttimes"	
}

traceroute_diagnostics_browse_instances_routehops() {
	local i=1
	local stc
	
	while read line
	do
		stc=`echo "$line" | grep "traceroute"`
		if [ -n "$stc" ];then
			continue
		fi
	
		sub_entry_routehops "$1" "$i" "$line"
		let i++
	done < /tmp/trace_info
		
	return 0
}

traceroute_get() {
	local val=`$UCI_GET_VARSTATE $1`
	echo ${val:-$2}
}

traceroute_set() {
	traceroute_stop_diagnostic
	if [ "`$UCI_GET_VARSTATE easycwmp.@local[0].DiagnosticsState_trace`" != "Requested" ]; then
		$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_trace=None
	fi
	$UCI_SET_VARSTATE $1=$2
	return 0
}

traceroute_set_number() {
	case $2 in
		(*[^0-9]*|'') return $E_INVALID_PARAMETER_VALUE;;
	esac
	[ $2 -lt 1 ] && return $E_INVALID_PARAMETER_VALUE
	traceroute_stop_diagnostic
	if [ "`$UCI_GET_VARSTATE easycwmp.@local[0].DiagnosticsState_trace`" != "Requested" ]; then
		$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_trace=None
	fi
	$UCI_SET_VARSTATE $1=$2
	return 0
}

traceroute_set_diagnostic_state() {
	local val="$1"
	case $val in 
		Requested)
			traceroute_stop_diagnostic
			$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_trace=Requested
			common_execute_command_in_apply_service "/bin/sh $FUNCTION_PATH/traceroute_launch run &"
			return 0
		;;
	esac
	return $E_INVALID_PARAMETER_VALUE;
}

traceroute_stop_diagnostic() {
	local pids=`ps aux | grep traceroute_launch | grep -v grep | awk '{print $2}'`
	if [ -n "$pids" ]; then
		kill -9 $pids
		$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState_trace=None
	fi
}


