#!/bin/sh

usage() {
	echo "getmac <wl2 | wl1 | wl0 | lan | wan | wan2 | eth0 | eth1 *>"
	echo "example: getmac"
	echo "         getmac wan|eth0"
	echo "         getmac wan2"
	echo "         getmac lan|eth1"
	echo "         getmac wl0"
	echo "         getmac wl1"
	echo "         getmac wl2"
}

art_mtd=`cat /proc/mtd | grep ART | cut -d ":" -f 1`
[ -z "$art_mtd" ] && exit 1

get_eth0()
{
	eth0adr="`hexdump -s 0 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}

get_eth1()
{
	eth1adr="`hexdump -s 6 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}

get_wan2()
{
        wan2adr="`hexdump -s 12 -n 6 -e '6/1 "%02x:"'  /dev/"$art_mtd" | cut -b-17`"
}


#wifi0 wifi1都是soc0的子设备，用caldata.bin,wifi1.caldata存放soc1的子设备9889的wifi2的mac
get_wifi0()
{
	wifi0adr="`hexdump -s 14 -n 6 -e '6/1 "%02x:"' /tmp/IPQ5018/caldata.bin | cut -b -17`"
	[ "${wifi0adr}" == "" -o "$wifi0adr" = "ff:ff:ff:ff:ff:ff" ] && wifi0adr="`cat /sys/class/net/wifi0/address 2>/dev/null`"
	ath0adr="$wifi0adr"
}

get_wifi1()
{
	wifi1adr="`hexdump -s 14 -n 6 -e '6/1 "%02x:"' /tmp/IPQ5018/qcn9000/caldata_1.bin -e | cut -b -17`"
	[ "${wifi1adr}" == "" -o "$wifi1adr" = "ff:ff:ff:ff:ff:ff" ] && wifi1adr="`cat /sys/class/net/wifi1/address 2>/dev/null`"
	ath1adr="$wifi1adr"
}


get_wifi2()
{
	wifi2adr="`hexdump -s 6 -n 6 -e '6/1 "%02x:"' /tmp/wifi2.caldata | cut -b -17`"
	[ "${wifi2adr}" == "" -o "$wifi2adr" = "ff:ff:ff:ff:ff:ff" ] && wifi2adr="`cat /sys/class/net/wifi2/address 2>/dev/null`"
	ath2adr="$wifi2adr"
}

# eth0 eth1 2g 5g plc eth2 eth3 bt
case $1 in
	-h)
	usage
	;;

	wl0|wifi1)
	# wl0=5g iface, to adapt miwifi habit
	get_wifi1
	echo "$ath1adr"
	;;
	
	wl1|wifi0)
	# wl1=2.4g iface, to adapt miwifi habit
	get_wifi0
	echo "$ath0adr"
	;;

	wl2|wifi2)
	# wl2=5g iface, to adapt miwifi habit
	get_wifi2
	echo "$ath2adr"
	;;

	lan|eth1)
	get_eth1
	echo "$eth1adr"
	;;

	wan|eth0)
	get_eth0
	echo "$eth0adr"
	;;

        wan2)
        get_wan2
        echo "$wan2adr"
        ;;

	*)
	get_eth0
	get_eth1
	get_wan2
	get_wifi0
	get_wifi1
	echo "$eth1adr,$ath0adr,$ath1adr,$eth0adr,$wan2adr"
	;;
esac

