#!/bin/sh

ifconfig lo 127.0.0.1

CINIT=1

hostname `flash get HOST_NAME | cut -f2 -d= | sed 's/\"//g'`

mount -t proc proc /proc
mount -t ramfs ramfs /var
if [ -d "/hw_setting" ];then
    mount -t yaffs2 -o tags-ecc-off -o inband-tags /dev/mtdblock1 /hw_setting
fi

mkdir /var/tmp
#mkdir /var/web
mkdir /var/log
mkdir /var/run
mkdir /var/lock
mkdir /var/system
mkdir /var/dnrd
mkdir /var/avahi
mkdir /var/dbus-1
mkdir /var/run/dbus
mkdir /var/lib
mkdir /var/lib/misc
mkdir /var/home
mkdir /var/root
mkdir /var/tmp/net
#for crond rancho
mkdir -p /var/spool/cron/crontabs
: > /var/spool/cron/crontabs/root
chmod 777 /var/spool/cron/crontabs/root
###for tr069
mkdir /var/cwmp_default
mkdir /var/cwmp_config

if [ ! -f /var/cwmp_default/DefaultCwmpNotify.txt ]; then
	cp -p /etc/DefaultCwmpNotify.txt /var/cwmp_default/DefaultCwmpNotify.txt 2>/dev/null
fi

##For miniigd
mkdir /var/linuxigd
cp /etc/tmp/pics* /var/linuxigd 2>/dev/null

##For pptp
mkdir /var/ppp
mkdir /var/ppp/peers

#smbd
mkdir /var/config
mkdir /var/private
mkdir /var/tmp/usb
mkdir /var/tmp/mmc

#snmpd
mkdir /var/net-snmp

cp /bin/pppoe.sh /var/ppp/true
echo "#!/bin/sh" > /var/ppp/true
#echo "PASS"     >> /var/ppp/true

#for console login
cp /etc/shadow.sample /var/shadow
cp /etc/passwd.sample /var/passwd

#for weave
cp /etc/avahi-daemon.conf /var/avahi

#extact web pages
#cd /web
##flash extr /web
#cd /

 
mkdir -p /var/udhcpc
mkdir -p /var/udhcpd
cp /bin/init.sh /var/udhcpc/eth0.deconfig
echo " " > /var/udhcpc/eth0.deconfig
cp /bin/init.sh /var/udhcpc/eth1.deconfig
echo " " > /var/udhcpc/eth1.deconfig
cp /bin/init.sh /var/udhcpc/br0.deconfig
echo " " > /var/udhcpc/br0.deconfig
cp /bin/init.sh /var/udhcpc/wlan0.deconfig
echo " " > /var/udhcpc/wlan0.deconfig

if [ "$CINIT" = 1 ]; then
startup.sh
fi

# for wapi certs related
mkdir /var/myca
# wapi cert(must done before init.sh)
cp -rf /usr/local/ssl/* /var/myca/ 2>/dev/null
# loadWapiFiles >/dev/null 2>&1
 
# for wireless client mode 802.1x
mkdir /var/1x
cp -rf /usr/1x/* /var/1x/ 2>/dev/null
mkdir /var/openvpn
cp -rf /usr/share/openvpn/* /var/openvpn 2>/dev/null

# for tr069 easycwmp
cp -f /lib/datamodel.xml  /var/datamodel.xml 2>/dev/null
cp -f /lib/unvalued_jsons /var/unvalued_jsons 2>/dev/null
	
# Start system script
mtd_userdata.sh load 2>/dev/null
if [ ! -f /var/userdata/product.ini ]; then
	cp -f /web_cste/cgi-bin/product.ini /var/userdata/product.ini 2>/dev/null
fi

cp -f /etc/cs_watchdog.conf /var/cs_watchdog.conf
watchdog  -c /var/cs_watchdog.conf &

apply &
init.sh gw all
 
# modify dst-cache setting
echo "24576" > /proc/sys/net/ipv4/route/max_size
echo "180" > /proc/sys/net/ipv4/route/gc_thresh
echo 20 > /proc/sys/net/ipv4/route/gc_elasticity
# echo 35 > /proc/sys/net/ipv4/route/gc_interval
# echo 60 > /proc/sys/net/ipv4/route/secret_interval
# echo 10 > /proc/sys/net/ipv4/route/gc_timeout
 
# echo "4096" > /proc/sys/net/nf_conntrack_max
echo "131072" > /proc/sys/net/netfilter/nf_conntrack_max
echo "3600" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_established
echo "10" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait
echo "10" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_close
echo "30" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout
echo "180" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout_stream
echo "600" > /proc/sys/net/ipv4/netfilter/ip_conntrack_generic_timeout
# echo "1048576" > /proc/sys/net/ipv4/rt_cache_rebuild_count
echo "32" > /proc/sys/net/netfilter/nf_conntrack_expect_max

echo "20" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_syn_sent

# modify IRQ Affinity setting
# echo "3" > /proc/irq/33/smp_affinity

#echo 1 > /proc/sys/net/ipv4/ip_forward #don't enable ip_forward before set MASQUERADE
#echo 2048 > /proc/sys/net/core/hot_list_length

initgpio.sh

if [ -f /bin/cs_broker ]; then
cs_broker -c /etc/mosquitto.conf & 2>/dev/null
cste_sub -h 127.0.0.1 -t totolink/router/# & 2>/dev/null
fi

# start web server
#ls /bin/watchdog > /dev/null && watchdog 1000&
#boa
#-------------------carystudio app---------------------------------
crond &
csteDriverConnMachine &
lighttpd -f /lighttp/lighttpd.conf -m /lighttp/lib/
csteSys watchdogCfgUpdate
csteSys scheCtl
#------------------------------------------------------------------
#for IGMPSNOOP
#echo "200 3" > /proc/StormCtrl

