#!/bin/sh /etc/rc.common

START=96
STOP=96
USE_PROCD=1

NAME1='terminal_list'
PROG1='/usr/bin/terminal_list'

EXTRA_COMMANDS="status"
EXTRA_HELP="	status	show service status"

start_service() {

	# --------------
	echo " start $NAME1: $PROG1"
	procd_open_instance
	procd_set_param command  $PROG1
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance

}

reload_service() {
	rc_procd start_service "$@"
	return 0
}

status(){
	pgrep -l -f 'terminal_list' || echo 'service not running'
}

