#!/bin/sh /etc/rc.common

START=94
STOP=94
USE_PROCD=1

NAME1='sys_daemon'
PROG1='/usr/bin/sys_daemon'

EXTRA_COMMANDS="status"
EXTRA_HELP="	status	show service status"

start_service() {

	# --------------
	echo " start $NAME1: $PROG1"
	procd_open_instance
	procd_set_param command  $PROG1
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance

}

reload_service() {
	rc_procd start_service "$@"
	return 0
}

status(){
	pgrep -l -f 'sys_daemon' || echo 'service not running'
}

