#!/bin/sh

wan_port=$(uci -q get misc.sw_reg.sw_wan_port)
lan_ports=$(uci -q get misc.sw_reg.sw_lan_ports)
otype=""
status=""

for port in ${lan_ports} ${wan_port}; do
	status=$(swconfig dev switch0 port $port get link | cut -d: -f3 | awk '{print$1}')
	[ "$port" = "$wan_port" ] && otype="wan" || otype=""

	if [ -n "$status" -a "$status" = "up" ]; then
		echo "port $port:up    $otype"
	else
		echo "port $port:down    $otype"
	fi
done

