#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=meshd
PROG=/usr/sbin/meshd

scan_timewait=10
support_mesh_ver4=$(mesh_cmd support_mesh_version 4)
[ "$support_mesh_ver4" = "1" ] && scan_timewait=5

start_service() {
	local init_flag=$(uci -q get xiaoqiang.common.INITTED)
	local device=$(uci -q get misc.wireless.if_5G)
	local mac=$(uci -q get wireless.$device.macaddr)
	if [ "$init_flag" != "YES" ]; then
		procd_open_instance
		procd_set_param command "$PROG" -i wl0 -t $scan_timewait -a $mac
		procd_set_param respawn
		procd_close_instance
	fi
}
