#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=miwifi-discovery
PROG="/usr/sbin/miwifi-discovery"

start_service() {
    mesh_mode=$(uci -q get xiaoqiang.common.NETMODE)
    mesh_version=$(mesh_cmd max_mesh_version)

    [ "$mesh_mode" == "wifiapmode" ] && exit 0
    [ "$mesh_mode" == "whc_re" -a "$mesh_version" -lt "4" ] && exit 0

    INITTED=$(uci -q get xiaoqiang.common.INITTED)
    mesh_ifname=$(uci -q get misc.wireless.ifname_5G)

    if [ "$mesh_version" -ge "4" ]; then
        procd_open_instance
        [ -z "$mesh_mode" ] && mesh_mode="whc_re"
        procd_set_param command "$PROG" -v "$mesh_version" -i "$mesh_ifname" -m "$mesh_mode"
        procd_set_param respawn
        procd_close_instance
    elif [ "$INITTED" = "YES" ]; then
        procd_open_instance
        procd_set_param command "$PROG"
        procd_set_param respawn
        procd_close_instance
    fi
}
