#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/client_monitor>/dev/null


start_service() {
	procd_open_instance
	procd_set_param command "$PROG" 
	procd_set_param respawn 0
	procd_close_instance
}

