#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=85

USE_PROCD=1
PROG=/usr/sbin/cwmpd


start_service() {
	enable=`uci -q get cwmp.acs.enable`	
	if [ $enable -lt 1 ] ;then
		return
	fi

	procd_open_instance
	procd_set_param command "$PROG" 
	procd_set_param respawn 0
	procd_close_instance
}

