#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org


START=99

USE_PROCD=1
PROG=/usr/bin/noip2

wan_idx=0

section_enabled() {
	config_get_bool enable  "$1" 'enable'  0
	config_get_bool enabled "$1" 'enabled' 0
	[ $enable -gt 0 ] || [ $enabled -gt 0 ]
}

section_provider() {
	config_get provider  "$1" 'provider'
	[ "$provider" != "no-ip.com" ]
}

start_instance() {
	local s="$1"
	let wan_idx+=1;
	
	section_enabled "$s" || {
		return 1
	}
	section_provider "$s" && {
		return 1
	}
	
	conf="/var/no-ip2_$s.conf"

	$PROG -C -w $wan_idx -c $conf

	procd_open_instance
	procd_set_param command "$PROG" -w "$wan_idx" -c "$conf" -M	
	procd_close_instance
	
}

start_service() {
	config_load 'ddns'
	config_foreach start_instance 'service'
}

stop_service() {
	killall -SIGQUIT noip2
}

