#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

start_service() {
	[ "$(uci -q get system.@system[0].telnetd)" == 1 ] || exit 0

	procd_open_instance
	procd_set_param command "$PROG" -F -l /bin/login.sh
	procd_close_instance
}
