#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=60
USE_PROCD=1

BIN=xl2tpd
RUN_D="/var/run/xl2tpd"
PID_F="/var/run/xl2tpd.pid"

start_service() {
	rm -rf "$RUN_D"
	mkdir -p "$RUN_D"

	opmode_custom=`uci -q get system.opmode.opmode_custom`
	if [ "$opmode_custom" == "br" -o "$opmode_custom" == "rpt" ] ;then
		return
	fi

	wan_proto=`uci -q get network.vpn.proto`
	enable=`uci -q get xl2tpd.xl2tpd.enable`
	if [ "0$wan_proto" != "0l2tp" -a $enable -lt 1 ] ;then
		return
	fi

	procd_open_instance
	procd_set_param command $BIN -D -l -p "$PID_F"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	rm -rf "$RUN_D"
	rm -rf "$PID_F"
}
