#! /bin/sh

brctl addbr br0
brctl addbr br1
brctl setfd br0 1
brctl setfd br1 1

# make interface to be activated.
ifconfig br0 192.168.1.1 up
ifconfig br1 192.168.253.1 up
ifconfig eth0   up

echo 0 > /proc/sys/net/ipv6/conf/br0/autoconf
echo 0 > /proc/sys/net/ipv6/conf/br0/accept_ra

