#!/bin/sh /etc/rc.common

START=97
USE_PROCD=1

NAME1='usr_flow'
PROG1='/usr/bin/usr_flow'

EXTRA_COMMANDS="status"
EXTRA_HELP="	status	show service status"

start_service() {

	# --------------
	echo " start $NAME1: $PROG1"
	procd_open_instance      $NAME1
	procd_set_param command  $PROG1

	procd_set_param respawn 10 5 -1

	procd_set_param limits core="unlimited"
	procd_set_param stderr 1
	procd_set_param root root
	procd_close_instance

}

status(){
	pgrep -l -f 'usr_flow' || echo 'service not running'
}

