#!/bin/sh

if [ $# -lt 2 ]
then 
#	getmib2 0.1 txsc
	echo -e "Usage: $0 <interface> <mib>"
	echo -e "interface:"
	echo -e "0.0: wlan0-vap0"
	echo -e "0.1: wlan0-vap1"
	echo -e "0.2: wlan0-vap2"
	echo -e "0.3: wlan0-vap3"
	echo -e "0.4: wlan0-vap4"
	echo -e "0.9: wlan0-vxd"
	echo -e "1.0: wlan1-vap0"
	echo -e "1.1: wlan1-vap1"
	echo -e "1.2: wlan1-vap2"
	echo -e "1.3: wlan1-vap3"
	echo -e "1.4: wlan1-vap4"
	echo -e "1.9: wlan1-vxd"
	exit 1
fi

t1=`echo $1 | awk -F '.' '{print $1}'`
t2=`echo $1 | awk -F '.' '{print $2}'`
#echo $t1, $t2, $2

if [ $t1 -eq 0 ]
then 
case "$t2" in
	0)	iwpriv wlan0-vap0 get_mib $2
		;;
	1)  iwpriv wlan0-vap1 get_mib $2
		;;
	2)  iwpriv wlan0-vap2 get_mib $2
	    ;;
	3)  iwpriv wlan0-vap3 get_mib $2
	    ;;
	4)  iwpriv wlan0-vap4 get_mib $2
	    ;;
	9)  iwpriv wlan0-vxd get_mib $2
	    ;;
esac
else
case "$t2" in
	0)	iwpriv wlan1-vap0 get_mib $2
		;;
	1)  iwpriv wlan1-vap1 get_mib $2
		;;
	2)  iwpriv wlan1-vap2 get_mib $2
	    ;;
	3)  iwpriv wlan1-vap3 get_mib $2
	    ;;
	4)  iwpriv wlan1-vap4 get_mib $2
	    ;;
	9)  iwpriv wlan1-vxd get_mib $2
	    ;;
esac
fi