#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

export TSLIB_TSDEVICE=/dev/input/event0
export TSLIB_CALIBFILE=/tmp/pointercal
export TSLIB_CONFFILE=/etc/ts.conf
export TSLIB_PLUGINDIR=/lib
export TSLIB_FBDEVICE=/dev/fb0
export TSLIB_CONSOLEDEVICE=none
export GUI_FBDEVICE=/dev/fb0
export GUI_SEMAPHORE=/tmp/gui_semaphore

run_scripts() {
	for i in /etc/rc.d/$1*; do
		[ -x $i ] && $i $2 2>&1
	done
}

system_config() {
	config_get_bool foreground $1 foreground 0
}

. /lib/functions.sh

config_load system
config_foreach system_config system

if [ "$1" = "S" -a "$foreground" != "1" ]; then
	run_scripts "$1" "$2" &
else
	run_scripts "$1" "$2"
fi
