#!/bin/sh

usage(){
    cat << EOF
usage: router X led control:
       xled_on  : light the router's X leds
       xled_off : make all X leds to dark

       router X led timer control:
       xled_timer_on <hour of led_on time> <min of led_on time> <hour of led_off time> <min of led_off time>
       xled_timer_off

EOF
    exit 255
}

led_on(){
    status=$(uci -q get miled.settings.status)
    if [ $status -ge 5 ];then
        status=$((status-5))   
    fi
    uci set miled.settings.status=$status
    uci set miled.settings.action="on"
    uci commit miled

    ubus call miled refresh '{}'

    timer_is_mesh_cap && mesh_cmd sync_lite > /dev/null 2>&1 &
    return
}

led_off(){
    status=$(uci -q get miled.settings.status)
    if [ $status -lt 5 ];then
        status=$((status+5))
    fi
    uci set miled.settings.status=$status
    uci set miled.settings.action="off"
    uci commit miled

    ubus call miled refresh '{}'

    timer_is_mesh_cap && mesh_cmd sync_lite > /dev/null 2>&1 &
    return
}

timer_on(){
    local h_open="$1"
    local m_open="$2"
    local h_close="$3"
    local m_close="$4"
    local format="%s %s * * * %s"
    local script_open
    local script_close

    uci set miled.settings.XLED_TIMER=1
    uci set miled.settings.XLED_TIMER_OPEN="$h_open"":""$m_open"
    uci set miled.settings.XLED_TIMER_CLOSE="$h_close"":""$m_close"
    uci commit miled

    grep -v "/usr/sbin/xled_ctl" /etc/crontabs/root > /etc/crontabs/root.new

    script_open=$(printf "$format" "$m_open" "$h_open" "/usr/sbin/xled_ctl xled_on > /dev/null 2>&1")
    echo "$script_open" >> /etc/crontabs/root.new
    script_close=$(printf "$format" "$m_close" "$h_close" "/usr/sbin/xled_ctl xled_off > /dev/null 2>&1")
    echo "$script_close" >> /etc/crontabs/root.new

    mv /etc/crontabs/root.new /etc/crontabs/root
    /etc/init.d/cron restart
    return
}

timer_off(){
    uci set miled.settings.XLED_TIMER=0
    uci set miled.settings.XLED_TIMER_OPEN="00:00"
    uci set miled.settings.XLED_TIMER_CLOSE="00:00"
    uci commit miled

    grep -v "/usr/sbin/xled_ctl" /etc/crontabs/root > /etc/crontabs/root.new
    mv /etc/crontabs/root.new /etc/crontabs/root
    /etc/init.d/cron restart
    return
}

timer_is_mesh_cap(){
    local netmode
    local capmode

    netmode=$(uci -q get xiaoqiang.common.NETMODE)
    [ -z "$netmode" ] && return 1

    [ "${netmode:0:7}" = "whc_cap" ] && return 0
    if [ "${netmode:0:9}" = "lanapmode" ]; then
        capmode=$(uci -q get xiaoqiang.common.CAP_MODE)
        [ -n "$capmode" -a "$capmode" = "ap" ] && return 0
    fi

    return 1
}

run_with_lock()
{
  {
       flock -x -w 60 1000
       [ $? -eq "1" ] && { log "$$, ===== lock failed. exit 1" ; exit 1 ; }
       $@
       flock -u 1000
   } 1000<>/var/log/led_crond_lock.lock
}

#---------------- main ----------------#
NUM_PARAMS="$#"
case "$1" in
    "xled_on" )
        [ "$NUM_PARAMS" != "1" ] && usage
        led_on
        ;;

    "xled_off" )
        [ "$NUM_PARAMS" != "1" ] && usage
        led_off
        ;;

    "xled_timer_on" )
        [ "$NUM_PARAMS" != "5" ] && usage
        run_with_lock timer_on "$2" "$3" "$4" "$5"
        ;;

    "xled_timer_off" )
        [ "$NUM_PARAMS" != "1" ] && usage
        run_with_lock timer_off
        ;;

    * )
        usage
        ;;
esac
return

