function SLP(){this.moduleSpec;this.bandsProvided=this.DOUBLE;this.gSupportIPv6Firewall=this.gIpv6HostCtrlSupport=this.ipv6Support=this.customLedSupport=this.hnatSupport=this.alinkTestSupport=this.wolinkSupport=this.elinkSupport=this.modeSwitchSupport=this.macFilterSupport=this.wpsSupport=this.multiSsidSupport=this.cipherSupport5g4=this.cipherSupport5g1=this.cipherSupport5g=this.cipherSupport2g=this.cipherSupport=this.authSupport5g4=this.authSupport5g1=this.authSupport5g=this.authSupport2g=this.authSupport=
this.wifiSwitchSplitSupport=this.wifiSwitchSupport=this.gEasyMeshUpgradeSupport=this.guest5GSupport=this.bandSteeringProvided=!1;this.g11AXSupport={};this.gSmbCloudSupport=this.gSysModeSupport=this.gMWanLoadBalanceSupport=this.gSfpRateSupport=this.gGameSupport=this.gLagSupport=this.gIptvSupport=this.gMulWanSupport=this.gSupportPortManage=this.wlanHost5gSupport160MBandWidth=this.wpa3Support=this.ofdmaSupport5g4=this.ofdmaSupport5g1=this.ofdmaSupport5g=this.ofdmaSupport2g=this.twtSupport5g4=this.twtSupport5g1=
this.twtSupport5g=this.twtSupport2g=this.ofdmaSupport=this.twtSupport=this.muMimoSupport5g4=this.muMimoSupport5g1=this.muMimoSupport5g=this.muMimoSupport2g=!1;this.hostnameMaxLen=31;this.SINGLE=1;this.DOUBLE=2;this.TRIPLE=3;this.error={};this.wds={context:this,getData:function(c){this.getOptions=c;c=this.context;var a=this,b=uciWireless.dynData,d={};d[uciWireless.fileName]={};d[uciWireless.fileName][KEY_NAME]=[b.wds_2g];c.bandsProvided==c.TRIPLE?d[uciWireless.fileName][KEY_NAME].push(b.wds_5g1,b.wds_5g2):
c.bandsProvided==c.DOUBLE&&d[uciWireless.fileName][KEY_NAME].push(b.wds_5g);$.query(d,function(b){ENONE==b[ERR_CODE]?a.getOptions.success&&a.getOptions.success(b):a.getOptions.fail&&a.getOptions.fail(b)},void 0,!0)},setData:function(c,a){}};this.host={context:this,getData:function(c){this.getOptions=c;c=this.context;var a=this,b={};b[uciWireless.fileName]={};b[uciWireless.fileName][KEY_NAME]=[uciWireless.dynData.host_2g];c.bandsProvided==c.TRIPLE?b[uciWireless.fileName][KEY_NAME].push(uciWireless.dynData.host_5g1,
uciWireless.dynData.host_5g2):c.bandsProvided==c.DOUBLE&&b[uciWireless.fileName][KEY_NAME].push(uciWireless.dynData.host_5g);this.context.bandSteeringProvided&&b[uciWireless.fileName][KEY_NAME].push(uciWireless.secName.wlanBS);slp.moduleSpec.wifi_switch&&1==slp.moduleSpec.wifi_switch&&b[uciWireless.fileName][KEY_NAME].push(uciWireless.dynData.wifi_switch);$.query(b,function(b){ENONE==b[ERR_CODE]?a.getOptions.success&&a.getOptions.success(b):a.getOptions.fail&&a.getOptions.fail(b)},void 0,!0)},setData:function(c){this.setOptions=
c;this.stateChanged=!1;this.state=0;var a=this.setOptions.data,b=this;b.name=void 0!=this.setOptions.name?name:void 0;Object.keys(a).forEach(function(c){void 0==b.name&&(b.name=c);b.name==c&&(c==uciWireless.dynData.wifi_switch&&null!=a[c][uciWireless.dynOptName.enable]||c!=uciWireless.secName.wlanBS&&null!=a[c][uciWireless.dynOptName.enable]||c==uciWireless.secName.wlanBS&&null!=a[c][uciWireless.optName.wifiEnable]?(b.stateChanged=!0,b.state=0==a[c][uciWireless.dynOptName.enable]||0==a[c][uciWireless.optName.wifiEnable]?
0:1):b.stateChanged=!1)});this._checkWDS()},_checkWDS:function(){var c,a=this,b=this.name,d=this.setOptions.data[b];switch(b){case uciWireless.dynData.host_2g:c=uciWireless.dynData.wds_2g;break;case uciWireless.dynData.host_5g:c=uciWireless.dynData.wds_5g;break;case uciWireless.dynData.host_5g1:c=uciWireless.dynData.wds_5g1;break;case uciWireless.dynData.host_5g2:c=uciWireless.dynData.wds_5g2;break;default:c="all"}a.context.wds.getData({success:function(b){var g=!1;if("all"==c)for(var e in b[uciWireless.fileName]){if(b[uciWireless.fileName].hasOwnProperty(e)&&
1==b[uciWireless.fileName][e][uciWireless.dynOptName.enable]){g=!0;break}}else g=1==b[uciWireless.fileName][c][uciWireless.dynOptName.enable];g?"all"==c||null==d[uciWireless.dynOptName.channel]&&null==d[uciWireless.dynOptName.mode]&&null==d[uciWireless.dynOptName.bandwidth]?a.stateChanged&&0==a.state?confirmDialog.show({title:label.confirmTitle,content:label.wirelessSwitchTipForWDS,callback:function(b){!0==b?a._checkWPS():a.setOptions.fail&&a.setOptions.fail()}}):a._checkWPS():(alarmDialog.show({content:errStr.wlanInvalidOptionWithWDSEnabled}),
a.setOptions.resetPhyConfig&&a.setOptions.resetPhyConfig(),a.setOptions.fail&&a.setOptions.fail(b)):a._checkWPS()},fail:function(){a._checkWPS()}})},_checkWPS:function(){var c={},a=this,b;switch(this.name){case uciWireless.dynData.host_2g:b="wps_status_2g";break;case uciWireless.dynData.host_5g:b="wps_status_5g";break;case uciWireless.dynData.host_5g1:b="wps_status_5g1";break;case uciWireless.dynData.host_5g2:b="wps_status_5g4";break;default:b="all"}c[uciWireless.fileName]={};c[uciWireless.fileName][KEY_NAME]=
"wps_status";$.query(c,function(c){var f=0;if(ENONE==c[ERR_CODE])if("all"==b)for(var g in c[uciWireless.fileName].wps_status){if(c[uciWireless.fileName].wps_status.hasOwnProperty(g)&&1==c[uciWireless.fileName].wps_status[g]){f=1;break}}else f=c[uciWireless.fileName].wps_status[b];else EUNAUTH==c[ERR_CODE]&&(f=0);1==f?confirmDialog.show({title:label.confirmTitle,content:label.wpsConfigShowTip,callback:function(b){b?a._checkCurHost():a.setOptions.fail&&a.setOptions.fail()}}):a._checkCurHost()})},_checkCurHost:function(){var c=
{},a=this,b=this.name,d=this.context,f=uciWireless.dynData;c[uciHostsInfo.fileName]={};c[uciHostsInfo.fileName][KEY_TABLE]=[uciHostsInfo.dynData.online_host];a.stateChanged&&0==a.state?$.query(c,function(c){c=formatTableData(c[uciHostsInfo.fileName][uciHostsInfo.dynData.online_host]);for(var e,h=0,k=c.length;h<k;h++)if(e=c[h],1==e.is_cur_host){1==e.type?b==uciWireless.dynData.wifi_switch||b==uciWireless.secName.wlanBS||b==f.host_2g&&"0"==e.wifi_mode||b==f.host_5g&&"1"==e.wifi_mode||b==f.host_5g1&&
"2"==e.wifi_mode||b==f.host_5g2&&"3"==e.wifi_mode?(c=label.wirelessSwitchTip,d.moduleSpec.wifi_switch&&1==d.moduleSpec.wifi_switch&&b==uciWireless.dynData.wifi_switch&&(c=label.wifiAllSwitchCloseConfirm),confirmDialog.show({title:label.confirmTitle,content:c,callback:function(b){!0==b?a._send():a.setOptions.fail&&a.setOptions.fail()}})):a._send():a._send();break}}):a._send()},_send:function(){var c={},a=this;c[uciWireless.fileName]=this.setOptions.data;$.modify(c,function(b){ENONE==b[ERR_CODE]?b.dfs_wait_time&&
0!=b.dfs_wait_time?dfsDialog.show(b.dfs_wait_time,function(){a.setOptions.success&&a.setOptions.success()}):a.setOptions.success&&a.setOptions.success():a.setOptions.fail&&a.setOptions.fail(b)})}};this.protocol={context:this,getData:function(c,a){this.getOptions=c;var b={},d=uciProto.secName,f=this;b[uciProto.fileName]={};b[uciProto.fileName][KEY_NAME]=this.getOptions.type&&"IPv6"==this.getOptions.type?"undefined"!=typeof a&&2==a?[d.wanv62,d.dhcpv62,d.pppoev62,d.stav62]:[d.wanv6,d.dhcpv6,d.pppoev6,
d.stav6]:"undefined"!=typeof a&&2==a?[d.wan2,d.dhcp2,d.pppoe2,d.sta2]:[d.wan,d.dhcp,d.pppoe,d.sta];$.query(b,function(a){ENONE==a[ERR_CODE]&&f.getOptions.success&&f.getOptions.success(a)},void 0,!0)},setData:function(c,a){this.setOptions=c;var b;(b="undefined"!=typeof a&&2==a?this.setOptions.data[uciProto.secName.wan2]:this.setOptions.data[uciProto.secName.wan])&&null!=b[uciProto.optName.type]&&(this.type=b[uciProto.optName.type]);this._checkWDS()},_checkWDS:function(){var c=this;this.context.wds.getData({success:function(a){var b,
d=!1,f;for(f in a[uciWireless.fileName])if(a[uciWireless.fileName].hasOwnProperty(f)&&(b=a[uciWireless.fileName][f],1==b[uciWireless.dynOptName.enable])){d=!0;break}d?(alarmDialog.show({content:label.wanWDSTip}),c.setOptions.fail&&c.setOptions.fail(a)):c._checkBridgeMode()},fail:function(){c._checkBridgeMode()}})},_checkBridgeMode:function(){var c=this,a={};void 0!=this.context.moduleSpec.elink&&1==this.context.moduleSpec.elink?(a[uciNetwork.fileName]={},a[uciNetwork.fileName][KEY_NAME]=[uciNetwork.dynData.bridgestatus],
$.query(a,function(a){ENONE==a[ERR_CODE]?1==a.network.bridge_status.enable?(alarmDialog.show({content:"设备工作在桥模式，宽带拨号上网功能禁用。"}),c.setOptions.fail&&c.setOptions.fail(a)):c._send():c._send()})):this._send()},_send:function(){var c={},a=this;c[uciProto.fileName]=this.setOptions.data;$.modify(c,function(b){ENONE==b[ERR_CODE]?a.setOptions.success&&a.setOptions.success(b):a.setOptions.fail&&a.setOptions.fail(b)})}};this.guest={context:this,getData:function(c){this.getOptions=c;c={};var a=this;c[uciGuestNet.fileName]=
{};c[uciGuestNet.fileName][KEY_NAME]=[uciGuestNet.secName.wireless2G];void 0!=this.context.moduleSpec.guest5g&&1==this.context.moduleSpec.guest5g&&c[uciGuestNet.fileName][KEY_NAME].push(uciGuestNet.secName.wireless5G);$.query(c,function(b){ENONE==b[ERR_CODE]&&a.getOptions.success&&a.getOptions.success(b)},void 0,!0)},setData:function(c){this.setOptions=c;this._send()},_send:function(){var c={},a=this;c[uciGuestNet.fileName]=this.setOptions.data;$.modify(c,function(b){ENONE==b[ERR_CODE]?b.dfs_wait_time&&
0!=b.dfs_wait_time?dfsDialog.show(b.dfs_wait_time,function(){a.setOptions.success&&a.setOptions.success()}):a.setOptions.success&&a.setOptions.success():a.setOptions.fail&&a.setOptions.fail(b)})}};this.timeStamp=null;this.expire=1E3;this.wanStatus={};this.wanIdx=1;this.latestWanStatus=function(c,a,b){var d=this,f=(new Date).getTime();(void 0==a||!1==a)&&null!=this.timeStamp&&f-this.timeStamp<this.expire&&("undefined"==typeof b&&1==this.wanIdx||"undefined"!=typeof b&&this.wanIdx==b)?c&&c(this.wanStatus):
(a={},a[uciNetwork.fileName]={},a[uciNetwork.fileName][KEY_NAME]="undefined"!=typeof b&&2==b?uciNetwork.dynData.wanStatus2:uciNetwork.dynData.wanStatus,void 0!=this.moduleSpec.hnat&&1==this.moduleSpec.hnat&&(a[uciHNat.fileName]={},a[uciHNat.fileName][KEY_NAME]=uciHNat.secName.main),$.query(a,function(a){ENONE==a[ERR_CODE]&&(d.timeStamp=(new Date).getTime(),"undefined"!=typeof b&&2==b?(d.wanStatus=a[uciNetwork.fileName][uciNetwork.dynData.wanStatus2],d.wanIdx=b):(d.wanStatus=a[uciNetwork.fileName][uciNetwork.dynData.wanStatus],
d.wanIdx=1),a[uciHNat.fileName]&&1==a[uciHNat.fileName][uciHNat.secName.main][uciHNat.optName.enable]&&(d.wanStatus[uciNetwork.optName.upSpeed]=null,d.wanStatus[uciNetwork.optName.downSpeed]=null));c&&c(d.wanStatus)},void 0,!0))};this.getWiFiStatus=function(c){var a=$.Deferred(),b=$.Deferred(),d={};slp.host.getData({success:function(b){d[uciWireless.fileName]=b[uciWireless.fileName];a.resolve()}});slp.guest.getData({success:function(a){d[uciGuestNet.fileName]=a[uciGuestNet.fileName];b.resolve()}});
$.when(a,b).done(function(){"function"==typeof c&&c(d)})};this.init=function(c){var a=this,b={};b[uciFunction.fileName]={};b[uciFunction.fileName][KEY_NAME]=uciFunction.secName.newModuleSpec;$.query(b,function(b){if(ENONE==b[ERR_CODE]){a.moduleSpec=b[uciFunction.fileName][uciFunction.secName.newModuleSpec];a.bandSteeringProvided=1==a.moduleSpec[uciFunction.optName.wlanBS];a.guest5GSupport=1==a.moduleSpec[uciFunction.optName.guest5g];a.gEasyMeshUpgradeSupport=1==a.moduleSpec[uciFunction.optName.supportEyUp];
a.wifiSwitchSupport=1==a.moduleSpec[uciFunction.optName.wifiSwitch];a.wifiSwitchSplitSupport=1==a.moduleSpec[uciFunction.optName.wifiSwitchSplit];a.multiSsidSupport=1==a.moduleSpec[uciFunction.optName.supportMultiSsid];a.macFilterSupport=1==a.moduleSpec[uciFunction.optName.macFilterSupport];a.modeSwitchSupport=1==a.moduleSpec[uciFunction.optName.modeSwitchSupport];a.elinkSupport=1==a.moduleSpec[uciFunction.optName.elink];a.wolinkSupport=1==a.moduleSpec[uciFunction.optName.wolink];a.alinkTestSupport=
1==a.moduleSpec[uciFunction.optName.alinkTest];a.hnatSupport=1==a.moduleSpec[uciFunction.optName.hnat];a.customLedSupport=1==a.moduleSpec[uciFunction.optName.customLed];a.ipv6Support=1==a.moduleSpec[uciFunction.optName.ipv6];a.gIpv6HostCtrlSupport=1==a.moduleSpec[uciFunction.optName.supportIpv6HostCtrl];a.gSupportIPv6Firewall=1==a.moduleSpec[uciFunction.optName.supportIPv6Firewall];a.muMimoSupport2g=1==a.moduleSpec[uciFunction.optName.mumimo2g];a.muMimoSupport5g=1==a.moduleSpec[uciFunction.optName.mumimo5g];
a.muMimoSupport5g1=1==a.moduleSpec[uciFunction.optName.mumimo5g1];a.muMimoSupport5g4=1==a.moduleSpec[uciFunction.optName.mumimo5g4];a.gSfpRateSupport=a.moduleSpec[uciFunction.optName.sfpRate]==uciFunction.optValue.enable;a.gSupportPortManage=a.moduleSpec[uciFunction.optName.portManage]==uciFunction.optValue.enable;a.gMulWanSupport=-1!=$.inArray(uciPortConfig.secType.mwan,a.moduleSpec[uciFunction.optName.portSubFunc]);a.gIptvSupport=-1!=$.inArray(uciPortConfig.secType.iptv,a.moduleSpec[uciFunction.optName.portSubFunc]);
a.gLagSupport=-1!=$.inArray(uciPortConfig.secType.lag,a.moduleSpec[uciFunction.optName.portSubFunc]);a.gGameSupport=-1!=$.inArray(uciPortConfig.secType.game,a.moduleSpec[uciFunction.optName.portSubFunc]);a.gSmbCloudSupport=a.moduleSpec[uciFunction.optName.smbCloud]==uciFunction.optValue.enable;a.wpsSupport=1==a.moduleSpec[uciFunction.optName.supportPinWps]||1==a.moduleSpec[uciFunction.optName.wpsStaSupport];a.elinkSupport&&(a.wpsSupport=!1);void 0!=a.moduleSpec[uciFunction.optName.loadBalanceMode]&&
(a.gMWanLoadBalanceSupport=!0);void 0!=a.moduleSpec[uciSystem.secName.sysMode]&&(a.gSysModeSupport=!0);if(void 0!=a.moduleSpec[uciFunction.optName.wanPortIndexList]){a.ethLayoutList=a.moduleSpec[uciFunction.optName.ethLayout];a.devicePowerPos=a.moduleSpec[uciFunction.optName.powerPos];a.wanPortRateList={};a.wanPortRateDescList={};b=a.moduleSpec[uciFunction.optName.wanPortRateList];for(var f=a.moduleSpec[uciFunction.optName.wanPortRateDescList],g=a.moduleSpec[uciFunction.optName.wanPortIndexList],
e=0;e<g.length;e++)a.wanPortRateList[g[e]]=b[e].split("_"),a.wanPortRateDescList[g[e]]=f[e].split("_")}void 0!=a.moduleSpec[uciFunction.optName.wlanServiceAttr]&&(-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr].indexOf("auth")&&(a.authSupport=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr].indexOf("cipher")&&(a.cipherSupport=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr].indexOf("twt")&&(a.twtSupport=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr].indexOf("ofdma")&&
(a.ofdmaSupport=!0));void 0!=a.moduleSpec[uciFunction.optName.wlanServiceAttr2g]&&(-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr2g].indexOf("auth")&&(a.authSupport2g=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr2g].indexOf("cipher")&&(a.cipherSupport2g=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr2g].indexOf("twt")&&(a.twtSupport2g=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr2g].indexOf("ofdma")&&(a.ofdmaSupport2g=!0));void 0!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g]&&
(-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g].indexOf("auth")&&(a.authSupport5g=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g].indexOf("cipher")&&(a.cipherSupport5g=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g].indexOf("twt")&&(a.twtSupport5g=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g].indexOf("ofdma")&&(a.ofdmaSupport5g=!0));void 0!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g1]&&(-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g1].indexOf("auth")&&
(a.authSupport5g1=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g1].indexOf("cipher")&&(a.cipherSupport5g1=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g1].indexOf("twt")&&(a.twtSupport5g1=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g1].indexOf("ofdma")&&(a.ofdmaSupport5g1=!0));void 0!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g4]&&(-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g4].indexOf("auth")&&(a.authSupport5g4=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g4].indexOf("cipher")&&
(a.cipherSupport5g4=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g4].indexOf("twt")&&(a.twtSupport5g4=!0),-1!=a.moduleSpec[uciFunction.optName.wlanServiceAttr5g4].indexOf("ofdma")&&(a.ofdmaSupport5g4=!0));if(null!=a.moduleSpec[uciFunction.optName.channel5g1]){a.bandsProvided=a.TRIPLE;for(e=0;e<a.moduleSpec[uciFunction.optName.mode5g1].length;e++)if(-1!=a.moduleSpec[uciFunction.optName.mode5g1][e].search("ax")){a.g11AXSupport.wlan5g1=!0;break}for(e=0;e<a.moduleSpec[uciFunction.optName.mode5g4].length;e++)if(-1!=
a.moduleSpec[uciFunction.optName.mode5g4][e].search("ax")){a.g11AXSupport.wlan5g4=!0;break}}else if(null!=a.moduleSpec[uciFunction.optName.channel5g])for(a.bandsProvided=a.DOUBLE,e=0;e<a.moduleSpec[uciFunction.optName.mode5g].length;e++){if(-1!=a.moduleSpec[uciFunction.optName.mode5g][e].search("ax")){a.g11AXSupport.wlan5g=!0;break}}else a.bandsProvided=a.SINGLE;for(e=0;e<a.moduleSpec[uciFunction.optName.mode2g].length;e++)if(-1!=a.moduleSpec[uciFunction.optName.mode2g][e].search("ax")){a.g11AXSupport.wlan2g=
!0;break}if(void 0!=a.moduleSpec[uciFunction.optName.supportWlanAuthType2g])for(e=0;e<a.moduleSpec[uciFunction.optName.supportWlanAuthType2g].length;e++)if(parseInt(a.moduleSpec[uciFunction.optName.supportWlanAuthType2g][e])==uciWireless.dynOptValue.auth.psk2_sae3||parseInt(a.moduleSpec[uciFunction.optName.supportWlanAuthType2g][e])==uciWireless.dynOptValue.auth.sae3)a.wpa3Support=!0;a.hostnameMaxLen=a.moduleSpec[uciFunction.optName.hostnameMaxLen]||31}"function"==typeof c&&c()},void 0,!0)}}
var slp=new SLP;
(function(){Object.keys||(Object.keys=function(){var c=Object.prototype.hasOwnProperty,a=!{toString:null}.propertyIsEnumerable("toString"),b="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),d=b.length;return function(f){if("object"!==typeof f&&"function"!==typeof f||null===f)throw new TypeError("Object.keys called on non-object");var g=[],e;for(e in f)c.call(f,e)&&g.push(e);if(a)for(e=0;e<d;e++)c.call(f,b[e])&&g.push(b[e]);return g}}());Array.prototype.map||
(Array.prototype.map=function(c){var a,b,d;if(null==this)throw new TypeError("this is null or not defined");var f=Object(this),g=f.length>>>0;if("function"!==typeof c)throw new TypeError(c+" is not a function");1<arguments.length&&(a=arguments[1]);b=Array(g);for(d=0;d<g;){var e;d in f&&(e=f[d],e=c.call(a,e,d,f),b[d]=e);d++}return b});Array.prototype.forEach||(Array.prototype.forEach=function(c,a){var b,d;if(null==this)throw new TypeError(" this is null or not defined");var f=Object(this),g=f.length>>>
0;if("function"!==typeof c)throw new TypeError(c+" is not a function");1<arguments.length&&(b=a);for(d=0;d<g;){var e;d in f&&(e=f[d],c.call(b,e,d,f));d++}});Array.prototype.filter||(Array.prototype.filter=function(c){if(void 0===this||null===this)throw new TypeError;var a=Object(this),b=a.length>>>0;if("function"!==typeof c)throw new TypeError;for(var d=[],f=2<=arguments.length?arguments[1]:void 0,g=0;g<b;g++)if(g in a){var e=a[g];c.call(f,e,g,a)&&d.push(e)}return d});Array.prototype.map||(Array.prototype.map=
function(c,a){var b,d,f;if(null==this)throw new TypeError(" this is null or not defined");var g=Object(this),e=g.length>>>0;if("[object Function]"!=Object.prototype.toString.call(c))throw new TypeError(c+" is not a function");a&&(b=a);d=Array(e);for(f=0;f<e;){var h;f in g&&(h=g[f],h=c.call(b,h,f,g),d[f]=h);f++}return d})})();
